name: Go Lint & Build

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - '**.yml'
      - '**.mod'
      - '**.sum'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.20"

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest
        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
